### ISSUE TITLE
Add cabal-edit to the shell

### ISSUE THREAD

**Issue by dhess** [hackworthltd/haskell-hacknix#21]
https://github.com/sdiehl/cabal-edit

**Comment by brprice** [comment]
Note, however that

> Since this library works directly with the PackageDescription data structure it cannot handle Cabal files in their full generality. Instead we directly manipulate the internal structure used to represent the Cabal file which is not capable of representing all surface constructs. If your Cabal file currently uses:
> - Common stanzas
> -   Conditional blocks
>  -  Preprocessor definitions
>
> These constructs will be compiled into the PackageDescription and inlined if you use cabal-edit. This makes cabal-edit useful for small beginning projects and ones that don't use advanced Cabal features.

**Comment by brprice** [comment]
Looks like we did something local to viz in https://github.com/hackworthltd/viz/pull/104

**Comment by dhess** [comment]
Closed by https://github.com/hackworthltd/haskell-hacknix/commit/cd1b712c4faf33ed8c7de5082fc3d0955aa04ce0
